//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CADENA_LIBRERIAS
{
    public CADENA_LIBRERIAS()
    {
        this.CATALOGO_LIBRERIA = new HashSet<CATALOGO_LIBRERIA>();
        this.PUNTO_VENTA = new HashSet<PUNTO_VENTA>();
    }

    public int ID_LIBRERIA { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }

    public virtual ICollection<CATALOGO_LIBRERIA> CATALOGO_LIBRERIA { get; set; }
    public virtual ICollection<PUNTO_VENTA> PUNTO_VENTA { get; set; }
}
