//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CATALOGO_LIBRERIA
{
    public CATALOGO_LIBRERIA()
    {
        this.INVENTARIO_PDV = new HashSet<INVENTARIO_PDV>();
    }

    public int ID_LIBRERIA { get; set; }
    public long ISBN { get; set; }

    public virtual CADENA_LIBRERIAS CADENA_LIBRERIAS { get; set; }
    public virtual ICollection<INVENTARIO_PDV> INVENTARIO_PDV { get; set; }
    public virtual LIBRO LIBRO { get; set; }
}
