//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GENERO
{
    public GENERO()
    {
        this.USUARIO = new HashSet<USUARIO>();
        this.LIBRO = new HashSet<LIBRO>();
    }

    public int ID_GENERO { get; set; }
    public string GENERO1 { get; set; }

    public virtual ICollection<USUARIO> USUARIO { get; set; }
    public virtual ICollection<LIBRO> LIBRO { get; set; }
}
