//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class LISTA_LIBROS
{
    public int ID_USUARIO { get; set; }
    public long ISBN { get; set; }
    public Nullable<int> CALIFICACION { get; set; }
    public string OPINION { get; set; }
    public string ESTADO { get; set; }

    public virtual LIBRO LIBRO { get; set; }
    public virtual USUARIO USUARIO { get; set; }
}
