//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mobLibraryEntities : DbContext
    {
        public mobLibraryEntities()
            : base("name=mobLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CADENA_LIBRERIAS> CADENA_LIBRERIAS { get; set; }
        public DbSet<CATALOGO_LIBRERIA> CATALOGO_LIBRERIA { get; set; }
        public DbSet<GENERO> GENERO { get; set; }
        public DbSet<INVENTARIO_PDV> INVENTARIO_PDV { get; set; }
        public DbSet<LIBRO> LIBRO { get; set; }
        public DbSet<LISTA_LIBROS> LISTA_LIBROS { get; set; }
        public DbSet<PUNTO_VENTA> PUNTO_VENTA { get; set; }
        public DbSet<SOLICITUD_PEDIDO> SOLICITUD_PEDIDO { get; set; }
        public DbSet<SOLICITUD_TRASLADO> SOLICITUD_TRASLADO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
