//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDisenio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aspecto
    {
        public int idAspecto { get; set; }
        public string nbrAspecto { get; set; }
        public int probabilidadAspecto { get; set; }
        public int impactoAspecto { get; set; }
        public int puntajeAspecto { get; set; }
        public string descripcionAspecto { get; set; }
        public int idElemento_fk { get; set; }
    
        public virtual Elemento Elemento { get; set; }
    }
}
