//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDisenio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public int idCategoria { get; set; }
        public string descripcionCategoria { get; set; }
        public string nivelCategoria { get; set; }
        public int valorMinimo { get; set; }
        public int valorMaximo { get; set; }
        public int idEscala_fk { get; set; }
    
        public virtual EscalaPuntaje EscalaPuntaje { get; set; }
    }
}
