//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDisenio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elemento
    {
        public Elemento()
        {
            this.Aspecto = new HashSet<Aspecto>();
        }
    
        public int idElemento { get; set; }
        public string nbrElemento { get; set; }
        public string descripcionElemento { get; set; }
        public int idFactor_fk { get; set; }
        public Nullable<int> Impacto { get; set; }
        public Nullable<int> Probabilidad { get; set; }
    
        public virtual ICollection<Aspecto> Aspecto { get; set; }
        public virtual Factor Factor { get; set; }
    }
}
