//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDisenio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public Factor()
        {
            this.Elemento = new HashSet<Elemento>();
        }
    
        public int idFactor { get; set; }
        public string nbrFactor { get; set; }
        public bool tipoFactor { get; set; }
        public string descripcionFactor { get; set; }
        public int idRiesgo_fk { get; set; }
        public Nullable<int> Impacto { get; set; }
        public Nullable<int> Probabilidad { get; set; }
    
        public virtual ICollection<Elemento> Elemento { get; set; }
        public virtual Riesgo Riesgo { get; set; }
    }
}
