//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDisenio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeccionAprendida
    {
        public int idLeccionAprendida { get; set; }
        public string nbrLeccionAprendida { get; set; }
        public string descripcionLeccionAprendida { get; set; }
        public System.DateTime fchCreacion { get; set; }
        public int idProyecto_fk { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
    }
}
