//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDisenio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public Permiso()
        {
            this.Rol = new HashSet<Rol>();
        }
    
        public int idPermiso { get; set; }
        public string nbrPermiso { get; set; }
        public string descripcionPermiso { get; set; }
        public string codigoPermiso { get; set; }
    
        public virtual ICollection<Rol> Rol { get; set; }
    }
}
