//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDisenio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public Proyecto()
        {
            this.LeccionAprendida = new HashSet<LeccionAprendida>();
            this.Riesgo = new HashSet<Riesgo>();
        }
    
        public int idProyecto { get; set; }
        public string nbrProyecto { get; set; }
        public string descripcionProyecto { get; set; }
        public int idPortafolioProyecto_fk { get; set; }
        public int idEscalaPuntaje { get; set; }
    
        public virtual EscalaPuntaje EscalaPuntaje { get; set; }
        public virtual ICollection<LeccionAprendida> LeccionAprendida { get; set; }
        public virtual PortafolioProyectos PortafolioProyectos { get; set; }
        public virtual ICollection<Riesgo> Riesgo { get; set; }
    }
}
