//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDisenio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoRiesgo
    {
        public TipoRiesgo()
        {
            this.Riesgo = new HashSet<Riesgo>();
        }
    
        public int idTipoRiesgo { get; set; }
        public string nbrTipoRiesgo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Riesgo> Riesgo { get; set; }
    }
}
