//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDisenio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Riesgo = new HashSet<Riesgo>();
        }
    
        public int idUsuario { get; set; }
        public string nbrUsuario { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string email { get; set; }
        public int telefono { get; set; }
        public byte[] contraseña { get; set; }
        public int idRol_fk { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Riesgo> Riesgo { get; set; }
        public virtual Rol Rol { get; set; }

        public byte[] StringToBytes(String cadena)
        {
            System.Text.ASCIIEncoding codificador = new System.Text.ASCIIEncoding();
            return codificador.GetBytes(cadena);
        }
    }
}
